### PR TITLE
Add support for onPress

### LINKED ISSUE #6: No onPress property?
I'm quite surprised there's no onPress property here.  
Any reason for that or are PR welcome?

### PR DESCRIPTION
**Pull request by ghost**
Fixes #6

### CODE REVIEW

**Comment by ghost** [comment]
@alanshaw review/merge welcome 😉

**Comment by ghost** [comment]
@alanshaw Sorry to bug you again, I know things can get busy 😄  just pinging you in case you forgot about this PR. Could you review and let me know if this LGTY?

**Review by alanshaw — APPROVED** [review]
LGTM

**Comment by alanshaw** [comment]
Thank you @kytwb - sorry for the delay!

**Pull request merged**
